import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { NextProvider } from "@/redux/NextProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Lora } from 'next/font/google'
 
const lora = Lora({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>
          <NextProvider>
        <ThemeProvider>
            <Navbar />
            {children}
            <Footer />
        </ThemeProvider>
          </NextProvider>
      </body>
    </html>
  );
}
